FROM python:2.7

MAINTAINER Shahbaz Nazir "shahbaznazir1992@gmail.com"

# Copying the requirements for installation to take
# advantage of the caching.
ADD tgc tgc
ADD setup.py .
ADD run_tests.sh .
ADD requirements.txt .

RUN chmod +x run_tests.sh
RUN pip install -r requirements.txt

CMD ["./run_tests.sh"]
