app:
  restart: always
  image: shahbazn/shahbazn-tgc
  environment:
    - SERVICE_NAME=tgc
  ports:
    - "8080"
  command: gunicorn tgc:app -b :8080 --name app --log-level=debug --log-file=-

integ:
  image: shahbazn/shahbazn-tgc:test
  environment: 
    TEST_TYPE: integ 

test:
  image: shahbazn/shahbazn-tgc:test
