FROM python:2.7

MAINTAINER Shahbaz Nazir "shahbaznazir1992@gmail.com"

# Copying the requirements for installation to take
# advantage of the caching.
ADD run_integ_tests.sh .

RUN chmod +x run_integ_tests.sh

CMD ["./run_integ_tests.sh"]
