FROM python:2.7

MAINTAINER Shahbaz Nazir "shahbaznazir1992@gmail.com"

# Copying the requirements for installation to take
# advantage of the caching.
COPY tgc/ /tgc/
COPY setup.py /
COPY requirements.txt /
COPY run_tests.sh /
RUN pip install -r /requirements.txt
RUN python setup.py install

CMD ["/run_tests.sh"]
