app:
  restart: always
  image: shahbazn/shahbazn-tgc
  environment:
    - SERVICE_NAME=tgc

integ:
  image: shahbazn/shahbazn-tgc:test
  environment: 
    TEST_TYPE: integ 

test:
  image: shahbazn/shahbazn-tgc:test
  environment: 
    TEST_TYPE: unit
